// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qezevrvvgpwxhrtayobh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlemV2cnZ2Z3B3eGhydGF5b2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjYzOTYsImV4cCI6MjA2NDUwMjM5Nn0.wM75fJUNFbwjz62B5iMklK0XJnI44KL6eBKjynEROZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);