// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddjjfgykgdssmwqxmsaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkampmZ3lrZ2Rzc213cXhtc2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5MjQ1NTcsImV4cCI6MjA2NDUwMDU1N30.4Ph7MG7PuinnZLZ4mhitrLI1OzUbGox_LwuK_F2AajY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);